### ISSUE TITLE
🐛 [b.io] Ergebnisdarstellung von Beschlussempfehlungsabstimmungen

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-development#440]
## Bugreport
Bei bundestag.io scheint es einige Probleme mit dem Umwandeln von Beschlussempfehlungen in Ergebnisse zu geben, vgl. https://cdn.discordapp.com/attachments/840284548071292949/849985811231539241/Bildschirmfoto_2021-06-03_um_14.17.17.png. Uns ist das Problem in jüngerer Vergangenheit mehrfach reportet worden. Für den angehefteten Fall habe ich es überprüft. Es ist richtig (als Beschlussempfehlung) eingetragen und hätte auf dieser Basis umgedreht werden müssen. 

### fachlicher Hintergrund

Die (Nutzer-) Abstimmung in der App findet immer über den Antrag an sich (und nicht über die Beschlussempfehlung) statt. Nun kann es sein, dass im Plenarsaal des Bundestages nicht über den Antrag/das Gesetz abgestimmt wird, sondern über die dazugehörige Beschlussempfehlung. Dabei sind 2 Fälle denkbar: 

Fall 01: Der Ausschuss empfiehlt in seiner Beschlussempfehlung die Ablehnung des Antrags/Gesetzes
Fall 02: Der Ausschuss empfiehlt in seiner Beschlussempfehlung die Annahme des Antrags/Gesetzes

Im ersteren Fall 01 ist dann eine Zustimmung zur Beschlussempfehlung eine Ablehnung des Antrags, d.h. invers zu zählen
Im zweiten Fall 02 ist die Zustimmung zur Beschlussempfehlung auch eine Zustimmung zum Antrag, d.h. gleichlautend.

Wir haben eigentlich einen Service implementiert, der die ggfs. notwendigen Umrechnungen vornimmt, wenn Fall 01 vorliegt. Den Text des Plenarsaalprotokolls geben wir überdies im Original wieder, um dem Nutzer ein Gefühl dafür zu geben, in welcher Datenform wir die nicht-namentlichen Abstimmungen erhalten und darauf basierend in ein maschinenlesbares Ergebnis überführen. Auf diese Weise kann auch eine Kontrolle stattfinden, ob wir Sie korrekt übertragen haben – hier hat uns in der Vergangenheit schon einiges an Nutzerfeedback erreicht, falls uns ein Dreher unterlaufen ist.

**Comment by visionmakery** [comment]
Selbes Problem: https://democracy-app.de/antrag/241811/netzwerkdurchsetzungsgesetz-weiterentwickeln-nutzerrechte-staerken-meinungsfreiheit-in-sozialen-netzwerken-sicherstellen

Kann es sein, dass mit der Umstellung des DIP-Service die Information, ob über Beschlussempfehlung oder Antrag abgestimmt wird, fehlt?

**Comment by ManAnRuck** [comment]
Erste kleinere Maßnahme (falls wir überhaupt noch Daten bekommen) wäre eine weitere Prüfung hinzuzufügen.

Wenn ich mich recht erinnere, wird nur auf Beschlussempfehlung und deren Umkehrung geprüft. Jedoch wird der Zustand (Angenommen/Abgelehnt) nicht mit ausgewertet. Dies könnte die Fehleranfälligkeit verringern.
Jedoch, könnte dies zu größeren Verzögerungen der Ergebnisdarstellung führen, da in Vergangenheit die Daten nicht immer Zeitnah vollständig waren.

**Comment by diemusik** [comment]
Selbes Problem:

 - https://democracy-app.de/antrag/272264/patente-fuer-impfstoffe-freigeben-weder-wirtschaftliche-noch-nationale-interessen-duerfen-die-bekaempfung-der-pandemie-beeintraechtigen

**Comment by ManAnRuck** [comment]
TODO: Namentliche Abstimmungen checken (votingRecommendation)

**Comment by diemusik** [comment]
Noch eins gefunden:
 - https://democracy-app.de/antrag/269407/oekostromausbau-zukunftsfaehig-gestalten

**Comment by visionmakery** [comment]
done

**Comment by diemusik** [comment]
Weiterer Fehlerteufel: https://democracy-app.de/gesetzgebung/244877/dreiundsechzigstes-gesetz-zur-aenderung-des-grundgesetzes-gesetz-zur-begrenzung-der-amtszeit-des-bundeskanzlers

(Wichtig für Reality-Check FDP!)

**Comment by visionmakery** [comment]
done
