### ISSUE TITLE
🐛 [b.io] fehlende XML-Daten

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-development#461]
@elisamenne hat beim Eintragen der Ergebnisse festgestellt, dass unsere Software bei  ca. 60% aller Entschlüsse keine XML-Daten erfasst, woraus sie die Ergebnisse eintragen kann, vgl.  
<img width="1274" alt="Bildschirmfoto 2021-07-20 um 10 19 09" src="https://user-images.githubusercontent.com/32302889/126286665-9b24f0d9-fe91-4141-a501-b99a01d6bb21.png">

Als Work-Around kennt sie den Weg über die Dokumente. 
Vermutlich ist die DIP-Rest-API inkompatibel zu den XML's Plenarsaalprotokollen.

Aber bitte erst nach der 1.4 darum kümmern!

**Comment by ManAnRuck** [comment]
Sollte auf internal wieder gehen :)
Da es aber grad einige Änderungen gibt, muss ich erst noch diese abschließen und sicherstellen, dass keine Fehler auftreten bevor ich das hier auf production deployen kann.

**Comment by visionmakery** [comment]
kann ich bestätigen: geht in den meisten Fällen auf Internal wieder :)

**Comment by ManAnRuck** [comment]
Da mit dieser Änderung viele weiter Server Änderungen ausgespielt werden müssen, schalte ich das lieber nach meinem Urlaub live.

**Comment by hejjoe** [comment]
"Vermutlich ist die DIP-Rest-API inkompatibel zu den XML's Plenarsaalprotokollen." 

Das liegt vermutlich daran, dass das DIP (ID3) nicht dem Referat betreut, wo die Plenarsaalprotokolle (PD3) erstellt werden. Siehe auch [Organisationsplan](https://www.bundestag.de/parlament/verwaltung).

**Comment by ManAnRuck** [comment]
Änderungen sind nun live.
Ursprungsproblem, dass die Hilfetexte nicht mehr angezeigt worden sind, war übrigens, dass für die 20 LP diese nicht richtig bei uns eingespielt worden waren.
