### ISSUE TITLE
Html Tags im Abstract

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-development#462]
Beim import über die neue Schnittstelle werden HTML Tags mit importiert. (Siehe Inhalt)
Diese sollten wir vorher rausfiltern.

![IMG_E6039B16D852-1](https://user-images.githubusercontent.com/2183135/126350806-523904a9-a800-4c26-873d-317ff169ead8.jpeg)

**Comment by visionmakery** [comment]
Hab das Problem beim 1.4-Testen ebenfalls festgestellt: 
![IMG_7494](https://user-images.githubusercontent.com/32302889/127832196-1a900c20-38f0-4b35-8a2a-642bfb0fcd90.jpg)

**Comment by visionmakery** [comment]
@roschaefer Kannst Du Dich darum in der nächsten Zeit kümmern?

**Comment by roschaefer** [comment]
@visionmakery das ist schon eine Weile erledigt und wartet auf ein Review: https://github.com/demokratie-live/democracy-development/pull/464
