### ISSUE TITLE
🐛[b.io] kein Ergebnis bei Namentlicher Abstimmung

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-development#469]
Es scheint bei Namentlichen Abstimmungen noch zu unregelmäßigen Problemen zu kommen:

### Bundeswehreinsatz zur Evakuierung aus Afghanistan (25. August 2021)
https://admin.bundestag.io/procedure/281130 bekommt kein Ergebnis, obwohl Ergebnis gemäß https://www.bundestag.de/parlament/plenum/abstimmung/abstimmung?id=753 vorliegt.

### Epidemische Lage von nationaler Tragweite (25. August 2021)
Bei https://admin.bundestag.io/procedure/281340 & https://www.bundestag.de/parlament/plenum/abstimmung/abstimmung?id=754 hat es scheinbar geklappt.

**Comment by ManAnRuck** [comment]
Hierbei scheint es sich um ein Redaktionsfehler auf Seiten des Bundestags zu handeln.

Anbei ist ersichtlich, dass ein Dokument einer komplett anderen Prozedur referenziert wird.

<img width="1319" alt="Bildschirmfoto 2021-11-13 um 17 27 37" src="https://user-images.githubusercontent.com/2183135/141651391-c117c5b4-c543-4b80-94ae-50845818d552.png">

**Comment by visionmakery** [comment]
Hey @ManAnRuck, sind das rechts im Bild DIP-Daten?

**Comment by ManAnRuck** [comment]
Ja über die dip api

**Comment by visionmakery** [comment]
Email an den Bundestag ist raus!

**Comment by ManAnRuck** [comment]
Nach der Anpassung der Redaktion des Bundestages, wird das Ergebnis nun korrekt angezeigt 👍🏼
