### ISSUE TITLE
🐛[b.io] fälschliche Umdrehung bei 244877

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-development#470]
Obwohl das Ergebnis gemäß Beschlusstext unter https://admin.bundestag.io/procedure/244877 korrekt eingetragen ist, kommt es zu einer fälschlichen Umdrehung, vgl. https://democracy-app.de/gesetzgebung/244877/dreiundsechzigstes-gesetz-zur-aenderung-des-grundgesetzes-gesetz-zur-begrenzung-der-amtszeit-des-bundeskanzlers. 

Kann es sein, dass da ein Beschlussemfehlungsmarker im Datensatz ist, der die Eintragung, obwohl nicht auf Beschlussempfehlung getoggelt, umdreht?

**Comment by ManAnRuck** [comment]
Hier handelt es sich um eine Abstimmung über die Gesetzgebung, nicht über die Beschlussempfehlung, daher wird es fälschlicherweise getauscht.

<img width="1051" alt="Bildschirmfoto 2021-09-15 um 21 00 03" src="https://user-images.githubusercontent.com/2183135/133493429-ba8e186e-e67d-48fe-884d-49141b379a6c.png">

**Comment by ManAnRuck** [comment]
@visionmakery hab's angepasst. 
Falls nach dem synchronisieren alles stimmt ticket gerne schließen

**Comment by visionmakery** [comment]
Ich hatte es vorher auf 'Gesetzgebung' und hab es dann bewusst auf 'Beschlussempfehlung' gestellt, um zu prüfen, ob eine manuelle Änderung etwas bewirkt. Offensichtlich besteht das Problem immer noch und ist doch tiefer liegend...

**Comment by ManAnRuck** [comment]
Inzwischen scheint es korrekt dargestellt zu werden.

![IMG_563648C5BF8D-1](https://user-images.githubusercontent.com/2183135/141650826-5e9a252a-4a46-4a32-829c-8b80e01e9ef5.jpeg)
