### ISSUE TITLE
New API Key for DIP API

### ISSUE THREAD

**Issue by hejjoe** [demokratie-live/democracy-development#489]
The old key is used here: 
https://github.com/demokratie-live/democracy-development/blob/master/bundestag.io/dip/.env
https://github.com/demokratie-live/democracy-development/blob/master/docker-compose.yml#L54
https://github.com/demokratie-live/democracy-development/blob/master/bundestag.io/dip/src/server.spec.ts#L21
https://github.com/demokratie-live/democracy-development/blob/master/infra/kustomize/overlays/local/bio-dip.env

> Zur Nutzung ist ein API-Key notwendig. Der zunächst bis Ende Mai 2023 gültige API-Key lautet:
> GmEPb1B.bfqJLIhcGAsH9fTJevTglhFpCoZyAAAdhp
> 
> Auf Anfrage können Sie auch einen eigenen API Key erhalten, der zeitlich unbefristet ist.
> 
> Bitte stellen Sie eine diesbezügliche Anfrage per E-Mail an: parlamentsdokumentation@bundestag.de

https://dip.bundestag.de/%C3%BCber-dip/hilfe/api#content

**Comment by ManAnRuck** [comment]
Danke @hejjoe 🙂
Keys sind nun angepasst.

ℹ️ In Production verwenden wir übrigens einen Angeforderten key.
